---
# Main Nornir configuration file

inventory:
  plugin: SimpleInventory
  options:
    host_file: "conf_test/hosts.yaml"
    group_file: "conf_test/groups.yaml"
    defaults_file: "conf_test/defaults.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 100

logging:
  #log_file: nornir.log # Optional: log to file
  level: DEBUG
  # format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" # Optional: custom format
  to_console: true
